# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160821_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='my_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appt',
            name='my_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
