# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20160821_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appt',
            name='my_date',
        ),
        migrations.RemoveField(
            model_name='appt',
            name='my_time',
        ),
    ]
