# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 17:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20160821_1306'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appt',
            managers=[
                ('ApptManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
