# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20161118_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='my_location',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
