# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20161118_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='appt',
            name='my_priority',
            field=models.CharField(default='Medium', max_length=12),
        ),
        migrations.AddField(
            model_name='appt',
            name='my_type',
            field=models.CharField(default='Appointment', max_length=12),
        ),
        migrations.AlterField(
            model_name='appt',
            name='my_location',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='appt',
            name='my_status',
            field=models.CharField(default='Pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='appt',
            name='my_symbol',
            field=models.CharField(default='&#x263a;', max_length=12),
        ),
        migrations.AlterField(
            model_name='appt',
            name='my_task',
            field=models.CharField(max_length=100),
        ),
    ]
