# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20161119_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='my_priority',
            field=models.CharField(default='None', max_length=12),
        ),
        migrations.AlterField(
            model_name='appt',
            name='my_symbol',
            field=models.CharField(default='&#x263a;', max_length=12),
        ),
        migrations.AlterField(
            model_name='appt',
            name='my_type',
            field=models.CharField(default='None', max_length=12),
        ),
    ]
