# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20161119_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appt',
            name='my_symbol',
        ),
    ]
