# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_appt_my_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt',
            name='my_type',
            field=models.CharField(max_length=20),
        ),
    ]
