# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20161121_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=18),
        ),
    ]
